---
title: "L-Dopa"
date: "April 30, 2016"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Load packages
library(readxl)
library(reshape2)
library(ggplot2)
library(knitr)

# Read in data
Dopa <- read_excel('ViPRoutput_LDopa_22-Apr-2016_clean.xlsx', 1, TRUE)

##### Set up dataframe

    # Remove first trials of Pt 110 at both baseline and F/U
    Dopa <- Dopa[-c(13, 16),]
    
    # Retain only columns of interest
    Dopa <- data.frame('ID' = as.factor(Dopa[['ID_Folder']]), 
                  'Assessment' = as.factor(rep(c('Baseline', 'Baseline', 'F/U', 'F/U'), times = 6)),
                  'Trial' = as.factor(rep(c('Trial 1', 'Trial 2'), times = 12)),
                  'Points' = Dopa[['5minBIN_Points']], 
                  'Valid clicks' = Dopa[['5minBIN_ValidClick']],
                  'Mean interval' = Dopa[['5minBIN_ValidClick_MeanInterval']])

##### Calculate mean performance, best trial by valid clicks, best trial by mean interval

    # Calculate participants' mean performance for each assessement
    mean_dat <- aggregate(cbind(Points, Valid.clicks, Mean.interval) ~ Dopa$ID + Dopa$Assessment, data = Dopa, mean)
    mean_dat <- mean_dat[ order(mean_dat[1], mean_dat[2]),]
    mean_dat <- cbind(mean_dat[1:2], 'Mean', mean_dat[3:5])
    names(mean_dat) <- names(Dopa)
    
    # Calculate participants' best trial at each assessment by valid clicks 
    best_clicks <- Dopa[
        as.numeric(by(Dopa, Dopa[c('Assessment', 'ID')], function(x) rownames(x)[which.max(x$Valid.clicks)])),]
    best_clicks <- cbind(best_clicks[1:2], 'Best clicks', best_clicks[4:6])
    names(best_clicks) <- names(Dopa)
        
    # Calculate participants' best trial at each assessment by mean interval (between valid clicks)
    best_interval <- Dopa[
        as.numeric(by(Dopa, Dopa[c('Assessment', 'ID')], function(x) rownames(x)[which.min(x$Mean.interval)])),]
    best_interval <- cbind(best_interval[1:2], 'Best interval', best_interval[4:6])
    names(best_interval) <- names(Dopa)
    
##### Add mean performance, best clicks, and best interval to original DF
Dopa_long <- rbind(Dopa, mean_dat, best_clicks, best_interval)
levels(Dopa_long[['Trial']]) <- c('Trial 1', 'Trial 2', 'Mean', 'Best clicks', 'Best interval')
Dopa_long <- Dopa_long[order(Dopa_long[1], Dopa_long[2], Dopa_long[[3]]),]
row.names(Dopa_long) <- NULL

##### Calculate percent change #####

    # Points
    Points_PC <- dcast(Dopa_long, ID + Trial ~ Assessment, value.var = 'Points')
    Points_PC$Points_PC <- paste0(round(100*
                                          (Points_PC$'F/U' - Points_PC$Baseline) / Points_PC$Baseline), '%')
    row.names(Points_PC) <- NULL

    # Valid clicks
    Clicks_PC <- dcast(Dopa_long, ID + Trial ~ Assessment, value.var = 'Valid.clicks')
    Clicks_PC$Clicks_PC <- paste0(round(100*
                                          (Clicks_PC$'F/U' - Clicks_PC$Baseline) / Clicks_PC$Baseline), '%')

    # Mean interval between clicks
    Interval_PC <- dcast(Dopa_long, ID + Trial ~ Assessment, value.var = 'Mean.interval')
    Interval_PC$Interval_PC <- paste0(round(100*
                                          (Interval_PC$'F/U' - Interval_PC$Baseline) / Interval_PC$Baseline), '%')
    Interval_PC[3:4] <- round(Interval_PC[3:4], 2)
```

```{r results='asis', echo=FALSE}

Dopa_round <- Dopa
Dopa_round['Mean.interval'] <- round(Dopa_round['Mean.interval'], 2)

kable(Dopa_round,
      col.names = c('Participant', 'Assessment', 'Trial', 'Points', 'Valid clicks', 'Mean interval'),
      row.names = FALSE,
      align = 'c')

##### Plotting Points

    # Trial 1 points
    
    ggplot(data = subset(Dopa_long, Trial == 'Trial 1'), aes(x=Assessment, y=Points, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Trial 1 --  Points') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Points_PC, Trial == 'Trial 1', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # Trial 2 points
    
    ggplot(data = subset(Dopa_long, Trial == 'Trial 2'), aes(x=Assessment, y=Points, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Trial 2 --  Points') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Points_PC, Trial == 'Trial 2', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # Mean of trial points
    
    ggplot(data = subset(Dopa_long, Trial == 'Mean'), aes(x=Assessment, y=Points, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Mean of trial points') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Points_PC, Trial == 'Mean', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

##### Plotting Valid clicks

   # Trial 1 clicks
    
    ggplot(data = subset(Dopa_long, Trial == 'Trial 1'), aes(x=Assessment, y=Valid.clicks, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Trial 1 --  Valid clicks') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Clicks_PC, Trial == 'Trial 1', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # Trial 2 scores
    
    ggplot(data = subset(Dopa_long, Trial == 'Trial 2'), aes(x=Assessment, y=Valid.clicks, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Trial 2 --  Valid clicks') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Clicks_PC, Trial == 'Trial 2', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # Mean of trial scores
    
    ggplot(data = subset(Dopa_long, Trial == 'Mean'), aes(x=Assessment, y=Valid.clicks, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Mean of valid clicks') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Clicks_PC, Trial == 'Mean', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # For trial with most valid clicks
        
    ggplot(data = subset(Dopa_long, Trial == 'Best clicks'), aes(x=Assessment, y=Valid.clicks, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Clicks in trials with most valid clicks') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Clicks_PC, Trial == 'Best clicks', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # For trial with smallest interval between clicks
    
    ggplot(data = subset(Dopa_long, Trial == 'Best interval'), aes(x=Assessment, y=Valid.clicks, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Clicks in trials with smallest intervals') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Clicks_PC, Trial == 'Best interval', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

##### Plotting Mean interval

   # Trial 1 intervals
    
    ggplot(data = subset(Dopa_long, Trial == 'Trial 1'), aes(x=Assessment, y=Mean.interval, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Trial 1 --  Mean intervals') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Interval_PC, Trial == 'Trial 1', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # Trial 2 intervals
    
    ggplot(data = subset(Dopa_long, Trial == 'Trial 2'), aes(x=Assessment, y=Mean.interval, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Trial 2 --  Mean intervals') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Interval_PC, Trial == 'Trial 2', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # Mean of trial mean intervals
    
    ggplot(data = subset(Dopa_long, Trial == 'Mean'), aes(x=Assessment, y=Mean.interval, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Mean of mean intervals') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Interval_PC, Trial == 'Mean', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # For trial with most valid clicks
        
    ggplot(data = subset(Dopa_long, Trial == 'Best clicks'), aes(x=Assessment, y=Mean.interval, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Intervals in trials with most valid clicks') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Interval_PC, Trial == 'Best clicks', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')

    # For trial with smallest interval between clicks
    
    ggplot(data = subset(Dopa_long, Trial == 'Best interval'), aes(x=Assessment, y=Mean.interval, group = ID, colour = ID)) + 
      geom_line() + 
      geom_point() +
      theme_bw() + 
      ggtitle('Intervals in trials with smallest intervals') + theme(plot.title=element_text(size = 20)) + 
      scale_colour_discrete(name = 'Participant')
    
    kable(subset(Interval_PC, Trial == 'Best interval', -2), 
          col.names = c('Participant', 'Baseline', 'Follow-up', 'Percent change'),
          row.names = FALSE,
          align = 'c')
```

